name: Build, Lint, Format and Type Check

on:
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Check formatting
        run: yarn format:check

      - name: Run linter
        run: yarn lint

      - name: Build application
        run: yarn build

      - name: Run type check (if using TypeScript)
        run: yarn typecheck
        continue-on-error: false
